// Generate build metadata into `.env.local` (gitignored) for Plasmo to inline
// into the bundle via process.env.PLASMO_PUBLIC_BUILD_*.
// Runs before every `plasmo dev` / `plasmo build` (chained in package.json scripts).
// Does NOT touch the version — that is bumped by scripts/bump-version.mjs in CI.
import { execSync } from "node:child_process"
import { readFileSync, writeFileSync } from "node:fs"
import { fileURLToPath } from "node:url"
import { dirname, resolve } from "node:path"

const here = dirname(fileURLToPath(import.meta.url))
const root = resolve(here, "..")
const pkgPath = resolve(root, "package.json")

const pkg = JSON.parse(readFileSync(pkgPath, "utf8"))

function run(cmd, fallback = "") {
  try {
    return execSync(cmd, { encoding: "utf8", cwd: root, stdio: ["pipe", "pipe", "ignore"] })
      .trim()
  } catch {
    return fallback
  }
}

const sha = run("git rev-parse --short HEAD", "dev")
const date = new Date().toISOString().slice(0, 10)
const branch =
  process.env.GITHUB_REF_NAME || run("git rev-parse --abbrev-ref HEAD", "main")

const lines = [
  "# Auto-generated by scripts/gen-version.mjs — do not edit.",
  `PLASMO_PUBLIC_BUILD_VERSION=${pkg.version}`,
  `PLASMO_PUBLIC_BUILD_SHA=${sha}`,
  `PLASMO_PUBLIC_BUILD_DATE=${date}`,
  `PLASMO_PUBLIC_BUILD_TAG=${branch}`,
  ""
]

writeFileSync(resolve(root, ".env.local"), lines.join("\n"))
console.log(
  `[gen-version] version=${pkg.version} sha=${sha} date=${date} tag=${branch}`
)